USE [BTESTE]
GO

/****** Object:  UserDefinedFunction [dbo].[RET_FAIXA_COMIS]    Script Date: 30/11/2015 09:43:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER function [dbo].[RET_FAIXA_COMIS](@FAIXA varchar(6),@VALOR FLOAT)
returns FLOAT

        as
        begin
                       
            declare @retorno FLOAT
            
            set @retorno = 

				(CASE WHEN 
					(SELECT LIMITE_FAIXA_1 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT PE_FAIXA_1 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT LIMITE_FAIXA_2 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT PE_FAIXA_2 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT LIMITE_FAIXA_3 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT PE_FAIXA_3 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_4 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_4 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_5 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_5 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_6 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_6 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_7 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_7 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_8 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_8 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_9 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_9 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_10 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_10 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_11 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_11 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_12 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_12 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT LIMITE_FAIXA_13 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_13 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_14 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_14 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_15 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_15 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_16 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_16 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_17 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_17 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_18 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_18 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_19 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_19 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_20 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_20 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_21 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_21 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_22 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_22 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_23 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_23 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_24 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_24 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					WHEN
					(SELECT Limite_faixa_25 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)>=@VALOR 
						THEN (SELECT Pe_faixa_25 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
					else (SELECT PE_FAIXA_1 FROM LFFAIXA WHERE CD_CODIGO=@FAIXA)
						END)
					
			 return @retorno
        end

GO


