--DELETE GECFG WHERE Sequencia IN (90001)


INSERT INTO [dbo].[GECFG]
           ([Sequencia]
           ,[Referencia]
           ,[Codigo_Modulo]
           ,[Divisao]
           ,[Ordem]
           ,[Descricao]
           ,[Senha]
           ,[Usuario_Criacao]
           ,[Sessao]
           ,[Tipo]
           ,[Picture]
           ,[Range]
           ,[Dado_Alpha]
           ,[Dado_Data]
           ,[Dado_Time]
           ,[Dado_Numeric]
           ,[Dado_Valor]
           ,[Dado_Logico]
           ,[Programa_F5]
           ,[Arquivo_CIGAM]
           ,[Campo_Arq_CIGAM]
           ,[Usuario_Modificacao]
           ,[Data_Modificacao]
           ,[Campo24]
           ,[Campo25]
           ,[Campo26]
           ,[Campo27]
           ,[Campo28]
           ,[Campo29]
           ,[Campo30]
           ,[Campo31]
           ,[Campo32]
           ,[Campo33]
           ,[Campo34]
           ,[Campo35]
           ,[Campo36]
           ,[Campo37]
           ,[Desabilitado]
           ,[Campo39]
           ,[Campo40]
           ,[Toltip]
           ,[Texto])
     VALUES
           (90001,
           '',
           'SP',
           '',
           1,
           'Usuário com permissão para alterar % comissão no pedido',
           '',
           '',
           '',
           'C',
           '5',
           '',
           '',
           '',
           '',
           '',
           '',
           '',
           '',
           0,
           0,
           '',
           '',
           '',
           '',
           '',
           '',
           0,
           0,
           0,
           'Sim',
           '',
           '',
           0,
           0,
           0,
           0,
           '',
           '',
           '',
           '',
           CONVERT(BINARY(20),''));

INSERT INTO [dbo].[GECFG]
           ([Sequencia]
           ,[Referencia]
           ,[Codigo_Modulo]
           ,[Divisao]
           ,[Ordem]
           ,[Descricao]
           ,[Senha]
           ,[Usuario_Criacao]
           ,[Sessao]
           ,[Tipo]
           ,[Picture]
           ,[Range]
           ,[Dado_Alpha]
           ,[Dado_Data]
           ,[Dado_Time]
           ,[Dado_Numeric]
           ,[Dado_Valor]
           ,[Dado_Logico]
           ,[Programa_F5]
           ,[Arquivo_CIGAM]
           ,[Campo_Arq_CIGAM]
           ,[Usuario_Modificacao]
           ,[Data_Modificacao]
           ,[Campo24]
           ,[Campo25]
           ,[Campo26]
           ,[Campo27]
           ,[Campo28]
           ,[Campo29]
           ,[Campo30]
           ,[Campo31]
           ,[Campo32]
           ,[Campo33]
           ,[Campo34]
           ,[Campo35]
           ,[Campo36]
           ,[Campo37]
           ,[Desabilitado]
           ,[Campo39]
           ,[Campo40]
           ,[Toltip]
           ,[Texto])
     VALUES
           (90002,
           '',
           'SP',
           '',
           1,
           'Usuário com permissão para alterar Cadastro de Comissão',
           '',
           '',
           '',
           'C',
           '5',
           '',
           '',
           '',
           '',
           '',
           '',
           '',
           '',
           0,
           0,
           '',
           '',
           '',
           '',
           '',
           '',
           0,
           0,
           0,
           'Sim',
           '',
           '',
           0,
           0,
           0,
           0,
           '',
           '',
           '',
           '',
           CONVERT(BINARY(20),''));
