--select * from GECFG_PLANO_DE_CONTA
INSERT INTO [dbo].[GECFG]
           ([Sequencia]
           ,[Referencia]
           ,[Codigo_Modulo]
           ,[Divisao]
           ,[Ordem]
           ,[Descricao]
           ,[Senha]
           ,[Usuario_Criacao]
           ,[Sessao]
           ,[Tipo]
           ,[Picture]
           ,[Range]
           ,[Dado_Alpha]
           ,[Dado_Data]
           ,[Dado_Time]
           ,[Dado_Numeric]
           ,[Dado_Valor]
           ,[Dado_Logico]
           ,[Programa_F5]
           ,[Arquivo_CIGAM]
           ,[Campo_Arq_CIGAM]
           ,[Usuario_Modificacao]
           ,[Data_Modificacao]
           ,[Campo24]
           ,[Campo25]
           ,[Campo26]
           ,[Campo27]
           ,[Campo28]
           ,[Campo29]
           ,[Campo30]
           ,[Campo31]
           ,[Campo32]
           ,[Campo33]
           ,[Campo34]
           ,[Campo35]
           ,[Campo36]
           ,[Campo37]
           ,[Desabilitado]
           ,[Campo39]
           ,[Campo40]
           ,[Toltip]
           ,[Texto])
     VALUES
           ( 90004,
           '',
           'SP',
           '',
           1,
           'Permisão de usuarios por unidade no livro e entrada',
           '',
           '',
           '',
           'A',
           '60',
           '',
           '',
           '',
           '',
           '',
           '',
           '',
           '',
           0,
           0,
           '',
           '',
           '',
           '',
           '',
           '',
           0,
           0,
           0,
           'Não',
           '',
           '',
           0,
           0,
           0,
           0,
           '',
           '',
           '',
           '',
           CONVERT(BINARY(1000),'Permisão de usuarios por unidade no livro e entrada'))